// script to append translations
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const translations = {
  en: {
    womansFashion: "Woman’s Fashion",
    mensFashion: "Men’s Fashion",
    electronics: "Electronics",
    homeLifestyle: "Home & Lifestyle",
    medicine: "Medicine",
    sportsOutdoor: "Sports & Outdoor",
    babyToys: "Baby’s & Toys",
    groceriesPets: "Groceries & Pets",
    healthBeauty: "Health & Beauty",
    todays: "Today’s",
    flashSales: "Flash Sales",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    sale: "SALE",
    addToCart: "Add To Cart",
    viewAllProducts: "View All Products",
    categories: "Categories",
    browseByCategory: "Browse By Category",
    phones: "Phones",
    computers: "Computers",
    smartWatch: "SmartWatch",
    camera: "Camera",
    headPhones: "HeadPhones",
    gaming: "Gaming",
    thisMonth: "This Month",
    viewAll: "View All",
    enhanceMusic: "Enhance Your Music Experience",
    buyNow: "Buy Now!",
    ourProducts: "Our Products",
    exploreProducts: "Explore Our Products",
    featured: "Featured",
    newArrival: "New Arrival",
    ps5: "PlayStation 5",
    ps5Desc: "Black and White version of the PS5 \n coming out on sale.",
    shopNow: "Shop Now",
    womensCollection: "Women’s Collections",
    womensCollectionDesc: "Featured woman collections that \n give you another vibe.",
    freeDeliveryTitle: "FREE AND FAST DELIVERY",
    freeDeliveryDesc: "Free delivery for all orders over $140",
    customerServiceTitle: "24/7 CUSTOMER SERVICE",
    customerServiceDesc: "Friendly 24/7 customer support",
    moneyBackTitle: "MONEY BACK GUARANTEE",
    moneyBackDesc: "We return money within 30 days"
  },
  ru: {
    womansFashion: "Женская мода",
    mensFashion: "Мужская мода",
    electronics: "Электроника",
    homeLifestyle: "Дом и интерьер",
    medicine: "Медицина",
    sportsOutdoor: "Спорт и отдых",
    babyToys: "Детские товары",
    groceriesPets: "Продукты и зоотовары",
    healthBeauty: "Красота и здоровье",
    todays: "Сегодняшнее",
    flashSales: "Горячие скидки",
    days: "Дни",
    hours: "Часы",
    minutes: "Минуты",
    seconds: "Секунды",
    sale: "СКИДКА",
    addToCart: "В корзину",
    viewAllProducts: "Смотреть все товары",
    categories: "Категории",
    browseByCategory: "Поиск по категориям",
    phones: "Телефоны",
    computers: "Компьютеры",
    smartWatch: "Умные часы",
    camera: "Камеры",
    headPhones: "Наушники",
    gaming: "Игры",
    thisMonth: "В этом месяце",
    viewAll: "Показать все",
    enhanceMusic: "Улучшите свой музыкальный опыт",
    buyNow: "Купить сейчас!",
    ourProducts: "Наши продукты",
    exploreProducts: "Изучите наши продукты",
    featured: "Популярное",
    newArrival: "Новые поступления",
    ps5: "PlayStation 5",
    ps5Desc: "Черно-белая версия PS5 \n выходит в продажу.",
    shopNow: "Купить",
    womensCollection: "Женские коллекции",
    womensCollectionDesc: "Популярные женские коллекции, которые \n подарят вам новое настроение.",
    freeDeliveryTitle: "БЕСПЛАТНАЯ И БЫСТРАЯ ДОСТАВКА",
    freeDeliveryDesc: "Бесплатная доставка для всех заказов от $140",
    customerServiceTitle: "СЛУЖБА ПОДДЕРЖКИ 24/7",
    customerServiceDesc: "Дружелюбная поддержка 24/7",
    moneyBackTitle: "ГАРАНТИЯ ВОЗВРАТА ДЕНЕГ",
    moneyBackDesc: "Мы возвращаем деньги в течение 30 дней"
  },
  tj: {
    womansFashion: "Мӯди занона",
    mensFashion: "Мӯди мардона",
    electronics: "Электроника",
    homeLifestyle: "Хона ва тарзи ҳаёт",
    medicine: "Тиб",
    sportsOutdoor: "Варзиш ва фароғат",
    babyToys: "Бачагона ва бозичаҳо",
    groceriesPets: "Хӯрокворӣ ва ҳайвонот",
    healthBeauty: "Саломатӣ ва зебоӣ",
    todays: "Имрӯза",
    flashSales: "Фурӯши фаврӣ",
    days: "Рӯз",
    hours: "Соат",
    minutes: "Дақиқа",
    seconds: "Сония",
    sale: "ТАХФИФ",
    addToCart: "Ба сабад",
    viewAllProducts: "Ҳамаи маҳсулотро дидан",
    categories: "Категорияҳо",
    browseByCategory: "Ҷустуҷӯ аз рӯи категория",
    phones: "Телефонҳо",
    computers: "Компютерҳо",
    smartWatch: "Соатҳои ҳушманд",
    camera: "Камераҳо",
    headPhones: "Гӯшмонакҳо",
    gaming: "Бозиҳо",
    thisMonth: "Дар ин моҳ",
    viewAll: "Ҳамаро дидан",
    enhanceMusic: "Таҷрибаи мусиқии худро беҳтар кунед",
    buyNow: "Ҳоло харед!",
    ourProducts: "Маҳсулоти мо",
    exploreProducts: "Маҳсулоти моро омӯзед",
    featured: "Машҳур",
    newArrival: "Навигарӣ",
    ps5: "PlayStation 5",
    ps5Desc: "Нусхаи сиёҳу сафеди PS5 \n ба фурӯш мебарояд.",
    shopNow: "Харидан",
    womensCollection: "Коллексияи занона",
    womensCollectionDesc: "Коллексияи машҳури занона, ки \n ба шумо эҳсоси нав мебахшад.",
    freeDeliveryTitle: "РАСОНДАНИ РОЙГОН ВА ЗУД",
    freeDeliveryDesc: "Расондани ройгон барои фармоишҳои зиёда аз $140",
    customerServiceTitle: "ХИЗМАТРАСОНӢ БА МИЗОҶОН 24/7",
    customerServiceDesc: "Дастгирии дӯстонаи 24/7",
    moneyBackTitle: "КАФОЛАТИ БАРГАРДОНИДАНИ ПУЛ",
    moneyBackDesc: "Мо пулро дар давоми 30 рӯз бармегардонем"
  }
};

const localesDir = path.join(__dirname, 'src', 'locales');

['en', 'ru', 'tj'].forEach(lang => {
  const filePath = path.join(localesDir, `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  data.translation = { ...data.translation, ...translations[lang] };
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});





